---

- import_tasks: pre-checks.yml

- import_tasks: get-version.yml
  when: kompose_version is not defined or not kompose_version

- import_tasks: download-kompose.yml

- import_tasks: install-kompose.yml

- import_tasks: post-checks.yml
