---

- name: Check the state of the new kompose package
  stat:
    path: "{{ kompose_install_dir }}/kompose"
  register: kompose_check_installed

- name: Fail play if kompose is not installed as expected
  assert:
    that:
      - kompose_check_installed.stat.exists
      - kompose_check_installed.stat.islnk
    fail_msg: kompose was not installed as expected, it is likely something went wrong.
    success_msg: kompose has been installed as expected.

- name: Check the kompose binary version matches the expected version
  shell: >
    set -o pipefail && \
      {{ kompose_install_dir }}/kompose version | \
      awk '{ print $1 }' | sed 's/^v//'
  args:
    executable: "{{ kompose_check_bash_path.stdout_lines[0] }}"
  changed_when: false
  failed_when: false
  register: kompose_check_installed_version

- name: Fail play if kompose is not the expected version
  assert:
    that:
      - kompose_check_installed_version.stdout_lines[0] == kompose_version
    fail_msg: Installed kompose version is not as expected, it is likely something went wrong.
    success_msg: Installed kompose version is as expected.
