---

- name: Check where bash is installed
  command: which bash
  register: kompose_check_bash_path
  failed_when: false
  changed_when: false

- name: Check for existing kompose binary
  stat:
    path: "{{ kompose_install_dir }}/kompose"
  register: kompose_check_existing

- name: Check kompose binary version if binary already exists
  shell: >
    set -o pipefail && \
      {{ kompose_install_dir }}/kompose version | \
      awk '{ print $1 }' | sed 's/^v//'
  args:
    executable: "{{ kompose_check_bash_path.stdout_lines[0] }}"
  changed_when: false
  register: kompose_check_existing_version
  when: kompose_check_existing.stat.exists
